name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[routes]]
pattern = "mail.hiyinni.cn"
zone_name = "hiyinni.cn"
custom_domain = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "d97decec-f09f-4cfd-acc6-ea80c96b8d4f"

[[kv_namespaces]]
binding = "kv"
id = "5463ac0c27274177991602563014edd8"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail-r2"

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
orm_log = false
domain = ["hiyinni.cn"]
admin = "admin@hiyinni.cn"
jwt_secret = "3cb43ce6f031e40bb6c519f08b6eb42c4fe94c41"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
